### ISSUE TITLE
Make the script an executable so no interpreters are required for it to run

### ISSUE THREAD

**Issue by lil-skelly** [brootware/PyMouseBot#1]
## Checklist

- [x] There are no similar reports on [existing issues](https://github.com/brootware/PyMouseBot/issues?q=is%3Aissue) (including closed ones).
- [x] I was in the `master` branch of the latest code.

**Comment by brootware** [comment]
Hey @CopernicusPY , thank you for the feedback. Are you referring to running the executable only and run only from within the root of the repo or are you talking about pushing this into a `PATH` to run as executable from any directory in an operating system?

**Comment by lil-skelly** [comment]
Best solution would be adding it into the PATH env, since it works with any operating system.
